# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Inspired with the help of https://technology.amis.nl/continuous-delivery/deploy-angular-and-node-js-webapp-in-azure-pipelines-part-5/

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Api
        steps:
          - checkout: self
            path: api
          - task: Npm@1
            inputs:
              command: 'ci'
              workingDir: '$(Pipeline.Workspace)/api'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                rm -f .gitignore
                rm -f README.md
              workingDirectory: '$(Pipeline.Workspace)/api'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Pipeline.Workspace)/api'
              artifact: 'api'
              publishLocation: 'pipeline'
  - stage: deployProduction
    displayName: Deploy Production
    dependsOn:
    - Build
    jobs:
      - deployment: VMDeploy_Production
        displayName: deploy Production
        environment:
          name: Prod
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                  - download: current
                    displayName: Download API
                    artifact: 'api'
                  - task: PowerShell@2
                    displayName: Api Deploy
                    inputs:
                      targetType: 'inline'
                      script: 'cp -Force -Recurse -Path $(Pipeline.Workspace)/api -Destination ${env:DESTFOLDER}'
                    env:
                      DestFolder: $(DestFolder)
                  - task: PowerShell@2
                    displayName: Env Deploy
                    inputs:
                      targetType: 'inline'
                      script: |
                        cp -Force -Path "${env:DESTFOLDER}/api/config/config.env.template" -Destination "${env:DESTFOLDER}/api/config/config.env"
                        (Get-Content "${env:DESTFOLDER}/api/config/config.env" -Raw) -replace '(PORT=).*',"`$11337" | Set-Content "${env:DESTFOLDER}/api/config/config.env"
                        (Get-Content "${env:DESTFOLDER}/api/config/config.env" -Raw) -replace '(MONGO_URI=).*',"`$1$(mongoUri)" | Set-Content "${env:DESTFOLDER}/api/config/config.env"
                        (Get-Content "${env:DESTFOLDER}/api/config/config.env" -Raw) -replace '(SESSION_SECRET=).*',"`$1$(sessSecret)" | Set-Content "${env:DESTFOLDER}/api/config/config.env"
                        (Get-Content "${env:DESTFOLDER}/api/config/config.env" -Raw) -replace '(DISCORD_CLIENT_ID=).*',"`$1$(discClientId)" | Set-Content "${env:DESTFOLDER}/api/config/config.env"
                        (Get-Content "${env:DESTFOLDER}/api/config/config.env" -Raw) -replace '(DISCORD_CLIENT_SECRET=).*',"`$1$(discClientSecret)" | Set-Content "${env:DESTFOLDER}/api/config/config.env"
                    env:
                      DestFolder: $(DestFolder)