# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Inspired with the help of https://technology.amis.nl/continuous-delivery/deploy-angular-and-node-js-webapp-in-azure-pipelines-part-5/

trigger:
- main

pool: Default
  #vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Api
        steps:
          - checkout: self
            path: api
          - task: NodeTool@0
            displayName: Ensure Node 15
            inputs:
              versionSpec: '15.x' 
              #force32bit: false # Optional
              checkLatest: true # Optional
          - task: Npm@1
            displayName: NPM CI
            inputs:
              command: 'ci'
              workingDir: '$(Pipeline.Workspace)/api'
          - task: PowerShell@2
            displayName: Remove extra files
            inputs:
              targetType: 'inline'
              script: |
                rm -Force .gitignore
                rm -Force README.md
              workingDirectory: '$(Pipeline.Workspace)/api'
          - task: PublishPipelineArtifact@1
            displayName: Publish Artifact in Pipeline
            inputs:
              targetPath: '$(Pipeline.Workspace)/api'
              artifact: 'api'
              publishLocation: 'pipeline'
  - stage: deployProduction
    displayName: Deploy Production
    dependsOn:
    - Build
    jobs:
      - deployment: VMDeploy_Production
        displayName: deploy Production
        environment:
          name: Prod
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                  - download: current
                    displayName: Download API
                    artifact: 'api'
                  - task: PowerShell@2
                    displayName: Api Deploy
                    inputs:
                      targetType: 'inline'
                      script: |
                        pm2 stop api
                        cp -Force -Recurse -Path $(Pipeline.Workspace)/api -Destination ${env:DESTFOLDER}
                    env:
                      DestFolder: $(DestFolder)
                  - task: PowerShell@2
                    displayName: Env Deploy
                    inputs:
                      targetType: 'inline'
                      script: |
                        cp -Force -Path "${env:DESTFOLDER}/api/config/config.env.template" -Destination "${env:DESTFOLDER}/api/config/config.env"
                        $content = Get-Content "${env:DESTFOLDER}/api/config/config.env"
                        $content = $content -replace '(?<Port>PORT=).*',"`${Port}1337"
                        $content = $content -replace '(?<Mongo>MONGO_URI=).*',"`${Mongo}$(mongoUri)"
                        $content = $content -replace '(?<SessSecret>SESSION_SECRET=).*',"`${SessSecret}$(sessSecret)"
                        $content = $content -replace '(?<DiscCliId>DISCORD_CLIENT_ID=).*',"`${DiscCliId}$(discClientId)"
                        $content = $content -replace '(?<DiscCliSecret>DISCORD_CLIENT_SECRET=).*',"`${DiscCliSecret}$(discClientSecret)"
                        $content | Set-Content "${env:DESTFOLDER}/api/config/config.env"
                        pm2 start api
                    env:
                      DestFolder: $(DestFolder)